language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'

env:
  global:
    - secure: OSnefJRzf314MPOlSHQwsh7RAj7mJRmxQXpgJYUi5cTfRs4DqDcYemLVuV4yH7yAt7RAJn2THbdYk86b42CQYqyKsTQWt2B4/Y8Xm9Mn0yUhsFtSajdJeNV28FqsMkSGYBvja48yLdDYIsy+j1KIfU0Ksoe01w01zeTx2XjaCihOq+AHsWu8/s3FlmfAytICXgvrJX4ZmKvQ1YC+LSQEiBWz6Qt4YPwFa4uk44Lxtqv/4C7L6sx4cHEaY4Vy8jndmTMScRDzJdJGfyVQbfCdnd6ihbV0aHJbPudpWJUwVnmt2OG0RhB8LRROqxYUKtFhPRzmdQOzBe6t/4TBUxusYv5LIBg3CXWAg9umsIpaxnVI7Bep7GR5N7w4FBPeYaDeKINRAq6hrebXCxgvso+OKmbXKdpJOhxr0Uzc90ZhZXj3TrUU0l9naNKD3NGWst34jgyqpv15ROjZ7VdRD/Tj05Q45oqVY8n8HqJyBWFqKSeujDLx+TSGtqpUoxBUPV5B8V0MuFqxg50PqnHGQViArL65qKllSwATmaGZjGYctPRXCVia/vU5blwksUNtee4THdddGbU4q3kz4h0mmbvYePnI7o8QmDNvCyyx/gFdHLBf+XssWZLs/naQpWfyl0jKju+COdE4ED21GEdaD1PnToq6riNXkvmsvfykupQvv3g=
    - secure: tb8FH4tPhcgprfd7NTEBLk/ZA6PMMDmjq4DIsIpubnsxaDEn56fVOkYNtTXMf8FJ8c8UYuW06mVfV0FCTRINLybb19ePK42P0pQoKi1V3WT+BKmWyWpoc4OAHKHZbvS8pvo4eF5vf2MlD4IJ2A9h0k/HYnB/pQquKJPw646CiUi3JwQ31SLuXmhquNlYJ24PlfQpoEO5DqPdHIyHR876s3jTAXgfBLAjWukGeLFmV3P4PZmcd+epDeAUDGY97e+zOyrtbRbQQa1eILiAk0TeqIwtIAkt+6n/kgGsFJG3u3REjSWr1por7cjOkQyC2xQjPbiWIWr+wia9+Jj3f1MbEAqRLnN2f+pwo5fh5bASivko3e+1slpOGd+UnygsD8jGWD7S7LFGQXGkSFhZLDTmKicrjo2u9UAfazGz4EGQdW+6EPkGi4xqZvX9U81bEoSxLmReIhkNvgRXDBRYHazBLpEnwIimpcW01IRRpOfT+D5XbfXQyMgQeXbKPTc8xHUaBuH4TDZT0+e8pR1YrKmRkGK4CzjJ4/Wh+Fytfs4bFhEwwfVVzgVxOfzuasQSptMPY3bsDVEfIEio2w2Y+ruifre6+jASJfUZxqCFm3fVUZfoH+ohsxmTffu7KqciOU+FzK+v7dGT2EdP2Vu4j+eX6vU4G0bjMJZFa4DDIWZswuA=
    - BLPAPI_VERSION=3.9.0
    - BLPAPI_CPP_VERSION=3.8.18.1
    - CONDA_VERSION=4.3.11

install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-${CONDA_VERSION}-Linux-x86_64.sh
    -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-${CONDA_VERSION}-Linux-x86_64.sh
    -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install conda-build
  - conda install anaconda-client

script:
  - bash build_package.sh

notifications:
  email: true
  slack:
    rooms:
      secure: "KgrpCWsUNO6VmBBcCs14eIp32r8keuL1RA17yTbgqCaSDo3OKo0VeCcJAZ3xWFM3icuLa0lIBhbvP2Wv/tYOmKgmdc8Lar6BsJkDRQ+2wOSz+z9k1pC47sKn/c+083XvRN7L/GXEMhP2wyDdLXDewLKnXeRKQYArJ7zUeojD+agk+RZI3dhmQrVKm/W1U+BMe8XJxYPu/JUhT/OiAxTDkFH9+G2Bi9QFNymIkyBgE8n9EXPt0Zjk7HKGRhp0u8F3EifjfPjra17ie9FW2IgHs6Pav7wd1tl5HTmOg7sFUmYmCLfOvkdoIYYFsUoHm1w/DSQqdWRhjVZhr0fAJSg/TmObwgxTczvZrwV2mRxqoIDU5EhFqyGTmoQ1fQ2/nc7zdgGvTH/wUbPZYgFP9fpF/95BYLUM4xB+2lnb+NwBwnt46vwjJkjC6XNo3dNZP0j2lnTz/Z5j+Kr7D1/cDq1B0Md5WZUk3dfWXWrLVwHduSz+DbfE9zzkmfOzn0z7H1LgF9m3xvFoI7p/lfZl6Ned1Cfq3FZlJe0vEMTHtYHz0RLiHqddwF9YhwWQL5H5ooR6yNxfFPrRBW+O96DBvfyNNx0Y3POBIxsPlRcid4NT2k/cWdh7bzQNhE4PNHgoeB+COVJ9eEHHWFVJC6y5+RMAkWN0BGtPLMTW2EuUHOziDYg="
